<?php
/**
 * Created by PhpStorm.
 * User: 呵.谢勇
 * Date: 2018/6/14
 * Time: 13:58
 */
namespace app\fire\validate;

class FireMaterialReserve extends BaseValidate {  
    protected $rule=[
        'region'=>'require|max:50|region',
        'location'=>'require|max:50',
        'established_time'=>'require',
        //'input_time'=>'require',
        'administrator'=>'require|max:20',
        'phone'=>'require|tel',
        'describe'=>'max:255',
        'gps'=>'require|number|between:1,99999999999',
        'fire_shovel'=>'require|number|between:1,99999999999',
        'wind_water_fire_extinguisher'=>'require|number|between:1,99999999999',
        'chain_saw'=>'require|number|between:1,99999999999',
        'dynamo'=>'require|number|between:1,99999999999',
        'high_pressure_mist_extinguisher'=>'require|number|between:1,99999999999',
        'water_pump'=>'require|number|between:1,99999999999',
        'dynamo_exploder'=>'require|number|between:1,99999999999',
        'broadax'=>'require|number|between:1,99999999999',
        'communication_van'=>'require|number|between:1,99999999999',
        'hacking_knife'=>'require|number|between:1,99999999999',
        'vehicular_locating_set'=>'require|number|between:1,99999999999',
        'clothing'=>'require|number|between:1,99999999999',
        'troop_crawler'=>'require|number|between:1,99999999999',
        'tent'=>'require|number|between:1,99999999999',
        'fire_fighting_water_wheel'=>'require|number|between:1,99999999999',
        'sleeping_bag'=>'require|number|between:1,99999999999',
        'fire_hoses'=>'require|number|between:1,99999999999',
        'rests'=>'require|number|between:1,99999999999',
        'two_three_tool'=>'require|number|between:1,99999999999',
        'uav'=>'require|number|between:1,99999999999',
        'pneumatic_extinguisher'=>'require|number|between:1,99999999999',
        'brush_cutter'=>'require|number|between:1,99999999999',
        'residual_fire_detector'=>'require|number|between:1,99999999999',
        'anemograph'=>'require|number|between:1,99999999999',
        'handheld_radio_equipment'=>'require|number|between:1,99999999999',
        'construction_area' => 'require|float|between:0.01,99999999.99',
        'duty'=>'require|max:20',
        

    ];
    protected $message=[
        'region.require'=>'区域必填',
        'region.max'=>'区域不能超过五十个字符',
        'location.require'=>'位置必填',
        'location.max'=>'位置不能超过五十个字符',
        'established_time.require'=>'成立时间必填',
        //'input_time.require'=>'录入时间必填',
        'administrator.require'=>'管理者必填',
        'administrator.max'=>'管理者不能超过二十个字符',
        'phone.require'=>'联系电话必填',
        //'describe.require'=>'描述必填',
        'describe.max'=>'描述不能超过二百五十五个字符',
        'gps.require'=>'GPS数量必填',
        'gps.number'=>'GPS数量必为整型',
        'gps.between'=>'GPS数量取值区间为：1至 99999999999',
        'fire_shovel.require'=>'消防铲数量必填',
        'fire_shovel.number'=>'消防铲数量必为整型',
        'fire_shovel.between'=>'消防铲数量取值区间为：1至 99999999999',
        'wind_water_fire_extinguisher.require'=>'风水灭火机数量必填',
        'wind_water_fire_extinguisher.number'=>'风水灭火机必数量为整型',
        'wind_water_fire_extinguisher.between'=>'风水灭火机取值区间为：1至 99999999999',
        'chain_saw.require'=>'油锯数量必填',
        'chain_saw.number'=>'油锯数量必为整型',
        'chain_saw.between'=>'油锯数量取值区间为：1至 99999999999',
        'dynamo.require'=>'发电机数量必填',
        'dynamo.number'=>'发电机数量必为整型',
        'dynamo.between'=>'发电机数量取值区间为：1至 99999999999',
        'high_pressure_mist_extinguisher.require'=>'高压细水雾灭火机数量必填',
        'high_pressure_mist_extinguisher.number'=>'高压细水雾灭火机数量必为整型',
        'high_pressure_mist_extinguisher.between'=>'高压细水雾灭火机数量取值区间为：1至 99999999999',
        'water_pump.require'=>'水泵数量必填',
        'water_pump.number'=>'水泵数量必为整型',
        'water_pump.between'=>'水泵数量取值区间为：1至 99999999999',
        'dynamo_exploder.require'=>'点火机数量必填',
        'dynamo_exploder.number'=>'点火机数量必为整型',
        'dynamo_exploder.between'=>'点火机数量取值区间为：1至 99999999999',
        'broadax.require'=>'大斧数量必填',
        'broadax.number'=>'大斧数量必为整型',
        'broadax.between'=>'大斧数量取值区间为：1至 99999999999',
        'communication_van.require'=>'通讯车数量必填',
        'communication_van.number'=>'通讯车数量必为整型',
        'communication_van.between'=>'通讯车数量取值区间为：1至 99999999999',
        'hacking_knife.require'=>'砍刀数量必填',
        'hacking_knife.number'=>'砍刀数量必为整型',
        'hacking_knife.between'=>'砍刀数量取值区间为：1至 99999999999',
        'vehicular_locating_set.require'=>'车载台数量必填',
        'vehicular_locating_set.number'=>'车载台数量必为整型',
        'vehicular_locating_set.between'=>'车载台数量取值区间为：1至 99999999999',
        'clothing.require'=>'服装数量必填',
        'clothing.number'=>'服装数量必为整型',
        'clothing.between'=>'服装数量取值区间为：1至 99999999999',
        'troop_crawler.require'=>'运兵车数量必填',
        'troop_crawler.number'=>'运兵车数量必为整型',
        'troop_crawler.between'=>'运兵车数量取值区间为：1至 99999999999',
        'tent.require'=>'帐篷数量必填',
        'tent.number'=>'帐篷数量必为整型',
        'tent.between'=>'帐篷数量取值区间为：1至 99999999999',
        'fire_fighting_water_wheel.require'=>'灭火水车数量必填',
        'fire_fighting_water_wheel.number'=>'灭火水车数量必为整型',
        'fire_fighting_water_wheel.between'=>'灭火水车数量取值区间为：1至 99999999999',
        'sleeping_bag.require'=>'睡袋数量必填',
        'sleeping_bag.number'=>'睡袋数量必为整型',
        'sleeping_bag.between'=>'睡袋数量取值区间为：1至 99999999999',
        'fire_hoses.require'=>'灭火水枪数量必填',
        'fire_hoses.number'=>'灭火水枪数量必为整型',
        'fire_hoses.between'=>'灭火水枪数量取值区间为：1至 99999999999',
        'rests.require'=>'其他数量必填',
        'rests.number'=>'其他数量必为整型',
        'rests.between'=>'其他数量取值区间为：1至 99999999999',
        'two_three_tool.require'=>'23号工具数量必填',
        'two_three_tool.number'=>'23号工具数量必为整型',
        'two_three_tool.between'=>'23号工具数量取值区间为：1至 99999999999',
        'uav.require'=>'无人机数量必填',
        'uav.number'=>'无人机数量必为整型',
        'uav.between'=>'无人机数量取值区间为：1至 99999999999',
        'pneumatic_extinguisher.require'=>'风力灭火机数量必填',
        'pneumatic_extinguisher.number'=>'风力灭火机数量必为整型',
        'pneumatic_extinguisher.between'=>'风力灭火机数量取值区间为：1至 99999999999',
        'brush_cutter.require'=>'割灌机数量必填',
        'brush_cutter.number'=>'割灌机数量必为整型',
        'brush_cutter.between'=>'割灌机数量取值区间为：1至 99999999999',
        'residual_fire_detector.require'=>'余火探测仪数量必填',
        'residual_fire_detector.number'=>'余火探测仪数量必为整型',
        'residual_fire_detector.between'=>'余火探测仪数量取值区间为：1至 99999999999',
        'anemograph.require'=>'风速仪数量必填',
        'anemograph.number'=>'风速仪数量必为整型',
        'anemograph.between'=>'风速仪数量取值区间为：1至 99999999999',
        'handheld_radio_equipment.require'=>'手持对讲机数量必填',
        'handheld_radio_equipment.number'=>'手持对讲机数量必为整型',
        'handheld_radio_equipment.between'=>'手持对讲机数量取值区间为：1至 99999999999',
        'construction_area.require'=>'建设面积必填',
        'construction_area.number'=>'建设面积必为数字',
        'construction_area.between'=>'建设面积取值区间为：1至 99999999.99',
        'duty.require'=>'职务必填',
        'duty.max'=>'职务不能超过二十个字符',

    ];
    protected $scene=[
        'add'=>['region','location','established_time','administrator','phone','describe','gps','fire_shovel','wind_water_fire_extinguisher','chain_saw','dynamo','high_pressure_mist_extinguisher','water_pump','dynamo_exploder','broadax','communication_van','hacking_knife','vehicular_locating_set','clothing','troop_crawler','tent','fire_fighting_water_wheel','sleeping_bag','fire_hoses','rests','two_three_tool','uav','pneumatic_extinguisher','brush_cutter','residual_fire_detector','anemograph','handheld_radio_equipment','construction_area','duty'],
        'edit'=>['region','location','established_time','administrator','phone','describe','gps','fire_shovel','wind_water_fire_extinguisher','chain_saw','dynamo','high_pressure_mist_extinguisher','water_pump','dynamo_exploder','broadax','communication_van','hacking_knife','vehicular_locating_set','clothing','troop_crawler','tent','fire_fighting_water_wheel','sleeping_bag','fire_hoses','rests','two_three_tool','uav','pneumatic_extinguisher','brush_cutter','residual_fire_detector','anemograph','handheld_radio_equipment','construction_area','duty'],
    ];
}