<?php
/**
 * Created by PhpStorm.
 * User: userYang
 * Date: 2018/5/29
 * Time: 11:01
 */
namespace app\fire\controller;

use think\console\Command;
use think\console\Input;
use think\console\Output;

/**
 * 定时任务计划
 * Class TimeTaskPlan
 * @package app\fire\controller
 */
class TimeTaskPlan extends Command {
    protected function initialize(Input $input, Output $output)
    {
        parent::initialize($input, $output); // TODO: Change the autogenerated stub
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('TimeTaskPlan')->getDescription('定时计划任务 TimeTask');
    }

    protected function execute(Input $input, Output $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
        $output->write();
    }
}